# Generated by Django 5.1.2 on 2024-10-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankLoan',
            fields=[
                ('Bln', models.CharField(max_length=20, primary_key='Bln', serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('LoanAmount', models.IntegerField()),
                ('Adress', models.CharField(max_length=300)),
                ('age', models.IntegerField()),
                ('phoneNO', models.IntegerField()),
            ],
        ),
    ]
